### ISSUE TITLE
Got Wrong Label in Test

### ISSUE THREAD

**Issue by thumarrushik** [amirsaffari/online-multiclass-lpboost#3]
Hello,

I have been applied Online Gradient Boosting-based on Decision tree Regression on the MAGIC Datasets (From UCI Machine Learning Repository). AS mentioned in the OMCBoost, I have done training of the Data. But When I predict on the model It gives the labels, which is the last label in the training. For Example, the Last label of the training sample is 1. It returns 1 in all the test data. So, I think, I did something wrong during the test the model. Can you send the pseudo code of test the model of online Gradient Boosting?

Thank you so much for your time.

**Comment by amirsaffari** [comment]
I simply used to use `./OMCBoost -c conf/omcb.conf --omclp --train --test` from the cmdline. 

Are you sure your train and test sets are different and you've them correctly in the config file?

**Comment by thumarrushik** [comment]
Can you mentioned out where is your code part for the test data? can pseudo code of test the model of online Gradient Boosting?

**Comment by amirsaffari** [comment]
Check this function and function bellow

https://github.com/amirsaffari/online-multiclass-lpboost/blob/master/src/experimenter.cpp#L52
